FROM postgres:12

# Create superuser by setting env variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

COPY ./init-dbs.sh /docker-entrypoint-initdb.d/init.sh
RUN chmod +x /docker-entrypoint-initdb.d/init.sh 


# # Set database env variables
# ENV LOCAL_NAME_DEV "devdb"
# ENV LOCAL_NAME_TEST "testdb"

