version: '3'

services:
  postgres:
    build: 
      context: ./postgres-migrations
      dockerfile: Dockerfile.postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    env_file:
      - .env

  migrations:
    build: 
      context: ./postgres-migrations
      dockerfile: Dockerfile.migrations
    container_name: migrations_container
    env_file:
      - .env
    volumes:
      - ./migrations/versions:/migrations/versions # Mounts reivisions directory over
      - ./postgres-migrations/dummy-data.csv:/dummy-data.csv
    depends_on:
      - postgres
