version: '3'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  migrations:
    build: 
      context: ./docker-migrations
      dockerfile: Dockerfile.migrations
    container_name: migrations_container
    env_file:
      - .env
    volumes:
      - ./migrations/versions:/migrations/versions # Mounts reivisions directory over
    depends_on:
      - db
