"""init

Revision ID: 2c1ff7d3332f
Revises: 
Create Date: 2023-08-09 20:24:28.130534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1ff7d3332f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('family_head', sa.String(), nullable=False),
    sa.CheckConstraint('client != family_head', name='check_client_head_entry_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_family')
    # ### end Alembic commands ###
