"""adding in client / family head names

Revision ID: 12e4e0e5ac80
Revises: b2828ec5cf74
Create Date: 2023-11-08 17:45:18.019283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e4e0e5ac80'
down_revision = 'b2828ec5cf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('family_head_name', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['client_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_family', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('family_head_name')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
